### ISSUE TITLE
How to build project

### ISSUE THREAD

**Issue by Ahorvath94** [Piraxus/Skybolt#1]
Hi all,

I am an aerospace engineer by trade and hence have not had extensive training on how to use CMake. Is there any chance that you could include a one-paragraph ish tutorial on how to use it and where to point CMake to, what options to use, etc? I am notoriously bad at understanding Cmake and the documentation for how to use it on their website is a little complicated. I have been frustrated with CMake many times on other projects as well.

Usage:

I opened CMake and set the source code directory to C:/Users/Owner/AppData/Local/Programs/Python/Python37/Lib/site-packages/Skybolt/     and I set the build directory to C:/Users/Owner/AppData/Local/Programs/Python/Python37/Lib/site-packages/Skybolt/bin  .   I used CMAKE_BUILD_TYPE --> RelWithDebInfo but I am not sure if I need to include CMAKE_INSTALL_PREFIX, other parameters etc. I also configured the compiler as MSVC 2017 and added 64 bit to that. I am using Windows 10 64 bit. Let me know what you think! Thanks for your help!

Here is the error message I got while building with CMake.

CMake Error at C:/Program Files/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find Boost (missing: thread date_time) (found version "1.72.0")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindBoost.cmake:2145 (find_package_handle_standard_args)
  src/Skybolt/AircraftHud/CMakeLists.txt:6 (find_package)

Detecting CXX compiler ABI info compiled with the following output:
Change Dir: C:/Users/Owner/AppData/Local/Programs/Python/Python37/Lib/site-packages/Skybolt/bin/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin/MSBuild.exe cmTC_21adf.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=15.0 /v:m && Microsoft (R) Build Engine version 15.5.180.51428 for .NET Framework

Copyright (C) Microsoft Corporation. All rights reserved.

  Microsoft (R) C/C++ Optimizing Compiler Version 19.12.25834 for x64

  Copyright (C) Microsoft Corporation.  All rights reserved.

  cl /c /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_21adf.dir\Debug\\" /Fd"cmTC_21adf.dir\Debug\vc141.pdb" /Gd /TP /errorReport:queue "C:\Program Files\CMake\share\cmake-3.17\Modules\CMakeCXXCompilerABI.cpp"

  CMakeCXXCompilerABI.cpp

**Comment by matthew-reid** [comment]
Your build issue is that CMake can't find boost. I'll write up a beginner tutorial for how to build with CMake and explain how to setup and find dependencies. I'll link the tutorial here once I've written it up, in a day or two.

**Comment by matthew-reid** [comment]
I wrote up a tutorial. Give this a try:
https://piraxus.com/2020/12/12/how-to-setup-cmake-build-environment-on-windows/

**Comment by Ahorvath94** [comment]
Alright! I will give it a try!

Thanks so much for your help!

**Comment by Ahorvath94** [comment]
I am getting closer but I think there are some issues with Boost and Cmake versions:

Looks like you need to have the most up to date Cmake and then run a very specific boost version and it should work

https://stackoverflow.com/questions/57415206/is-there-a-way-to-get-rid-of-the-new-boost-version-may-have-incorrect-or-missin

https://gitlab.kitware.com/cmake/cmake/-/issues/19658#note_620411

I managed to get a new error by changing out the FindBoost.cmake file with this one:

https://raw.githubusercontent.com/Kitware/CMake/master/Modules/FindBoost.cmake

Here is the error:

CMake Warning (dev) at C:/local/boost_1_75_0/tools/boost_install/BoostConfig.cmake:141 (find_package):
  Ignoring EXACT since no version is requested.
Call Stack (most recent call first):
  C:/local/boost_1_75_0/tools/boost_install/BoostConfig.cmake:215 (boost_find_component)
  C:/Program Files/CMake/share/cmake-3.19/Modules/FindBoost.cmake:588 (find_package)
  src/Skybolt/AircraftHud/CMakeLists.txt:6 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at C:/local/boost_1_75_0/tools/boost_install/BoostConfig.cmake:141 (find_package):
  Could not find a package configuration file provided by "boost_headers"
  with any of the following names:

    boost_headersConfig.cmake
    boost_headers-config.cmake

  Add the installation prefix of "boost_headers" to CMAKE_PREFIX_PATH or set
  "boost_headers_DIR" to a directory containing one of the above files.  If
  "boost_headers" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  C:/local/boost_1_75_0/tools/boost_install/BoostConfig.cmake:215 (boost_find_component)
  C:/Program Files/CMake/share/cmake-3.19/Modules/FindBoost.cmake:588 (find_package)
  src/Skybolt/AircraftHud/CMakeLists.txt:6 (find_package)

I tried adding boost_headers_DIR but I do not actually have a boost_headersConfig.cmake file or I cannot find it. I know this might be a boost-specific question so if you want to close it and move the discussion there can do that but it is preventing me from building this which I think is a really cool repo.

**Comment by matthew-reid** [comment]
boost_headersConfig.cmake is a fallback if find_package() fails, but it shouldn't be required. If find_package() fails, CMake automatically looks for XXXConfig.cmake (where XXX is the package name), which is why you're seeing that error message. With CMake you shouldn't need to touch XXX_DIR variables. The only variable you need to manually set for finding packages is the CMAKE_PREFIX_PATH environment variable. If the boost folder is in that path and it still can't find it, then it's a either a problem with the boost sdk or the boost find package script.

I'm using version boost 1.67 and have my boost sdk setup like this:

All the boost headers under: boost/include
All the boost libraries under: boost/lib
The 'boost' root directory is on my CMAKE_PREFIX_PATH

I hope that helps. I'll close this ticket since it's a boost/cmake issue. If you make further progress please raise new tickets for other issues.
