### ISSUE TITLE
Regarding all applications (FlightSimApp/MinimalApp) crashes [Resolved]

### ISSUE THREAD

**Issue by mmmovania** [Piraxus/Skybolt#10]
Hi,
   I have successfully build the skybolt engine on windows. When I run the MinimalApp or FlightSimApp, the application closes and the console has this written. Can you please share why the textures are not loaded when they are contained in the Assets folder.

[2022-04-04 19:24:44.439233] [0x00001cd0] [info]    Reading settings file '"XYZ:\\Skybolt-master\\src\\SkyboltExamples\\Exa
mplesCommon\\ExampleSettings.json"'
[2022-04-04 19:24:44.442236] [0x00001cd0] [info]    8 CPU cores detected.  Creating 7 background threads.
[2022-04-04 19:24:44.448242] [0x00001cd0] [info]    Registered asset package: Assets
[2022-04-04 19:24:44.448242] [0x00001cd0] [info]    Registered asset package: Core
void StateSet::setGlobalDefaults() ShaderPipeline disabled.
Error reading file Environment/Space/SunDisc.png: file not found
Error reading file Environment/Space/MoonDisc.jpg: file not found
Could not open image file: Environment/Space/MoonDisc.jpg

XYZ:\\Skybolt-master\build\bin\Debug\FlightSimApp.exe (process 688) exited with code 0.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .

**Comment by mmmovania** [comment]
Some more details.  I have the asset UH60 downloaded under Assets\Movers\Models\UH60 but still i get the error loading UH60.

**Comment by mmmovania** [comment]
I guess the dynamicsmodel is need for flight sim app. MinimalApp works fine. THe issue is resolved.

**Comment by matthew-reid** [comment]
@mmmovania The flight sim app has a runtime dependency on the Bullet plugin, which must be built to run the app. I'm sorry that is not very clear in the error message. I'll add improving the error message to my list of tasks.
