### ISSUE TITLE
Link for Seattle data not working

### ISSUE THREAD

**Issue by Atlis** [Piraxus/Skybolt#14]
The link for the Seattle data (provided in `README.md`) does not seem to work:
[https://f000.backblazeb2.com/file/skybolt/Seattle_1_1_0.zip](https://f000.backblazeb2.com/file/skybolt/Seattle_1_1_0.zip)

**Comment by matthew-reid** [comment]
The file was misnamed on the server. The link should work now.

**Comment by Atlis** [comment]
It works now. Thanks.
