### ISSUE TITLE
[Question] StarField coordinates

### ISSUE THREAD

**Issue by bbbbx** [Piraxus/Skybolt#19]
[BrightStarCatelog](https://github.com/Piraxus/Skybolt/blob/master/src/Skybolt/SkyboltVis/Renderable/Stars/BrightStarCatelog.cpp) seems alreay in radians unit, maybe it shouldn't multipliy 24 in 
https://github.com/Piraxus/Skybolt/blob/master/src/Skybolt/SkyboltVis/Renderable/Stars/Starfield.cpp#L64 ?

**Comment by matthew-reid** [comment]
Good find. Fixed in [be69f6ca737dfdaf3163b9cd37fcdae40c3ba3f0](https://github.com/Piraxus/Skybolt/commit/be69f6ca737dfdaf3163b9cd37fcdae40c3ba3f0)
