### ISSUE TITLE
example can't be run

### ISSUE THREAD

**Issue by huidian200803** [Piraxus/Skybolt#4]
The example   can't run，
there is no  entityFactory.createEntity("Camera");
EntityPtr planet = entityFactory.createEntity("PlanetEarth");
....
example will crash.

**Comment by matthew-reid** [comment]
Hi Huidian,

Are you getting errors saying the "Camera" entity can't be found? Please ensure you've downloaded the Core asset pack and put the folder in the correct location relative to the program working directory as per the instructions in the "Install Asset Packages" section of the [readme](https://github.com/Piraxus/Skybolt/blob/master/README.md).

**Comment by matthew-reid** [comment]
Hi @huidian200803, have you had any success? If so I'll close this issue.

**Comment by huidian200803** [comment]
Hi   @matthew-reid , i have succeeded, thank you very much~!
