### ISSUE TITLE
Error while linking FlightSimApp 

### ISSUE THREAD

**Issue by marek-cel** [Piraxus/Skybolt#8]
While linking FlightSimApp on LinuxMint 20.1 (Ubuntu 20.04 LTS) i got this error:
Linking CXX executable ../../../bin/FlightSimApp
/usr/bin/ld: ../../../lib/libExamplesCommon.a(HudSystem.cpp.o): in function `skybolt::HudSystem::updatePostDynamics(skybolt::sim::System::StepArgs const&)':
/home/cel/Projekty/var/Skybolt/master/Skybolt-master/src/SkyboltExamples/ExamplesCommon/HudSystem.cpp:170: undefined reference to `skybolt::HeadingRibbonModel::draw(float, float*)'
/usr/bin/ld: /home/cel/Projekty/var/Skybolt/master/Skybolt-master/src/SkyboltExamples/ExamplesCommon/HudSystem.cpp:178: undefined reference to `skybolt::HudHoverVelModel::draw(glm::vec<2, float, (glm::qualifier)0> const&)'
/usr/bin/ld: /home/cel/Projekty/var/Skybolt/master/Skybolt-master/src/SkyboltExamples/ExamplesCommon/HudSystem.cpp:185: undefined reference to `skybolt::PitchLadderModel::draw(float, float)'
/usr/bin/ld: /home/cel/Projekty/var/Skybolt/master/Skybolt-master/src/SkyboltExamples/ExamplesCommon/HudSystem.cpp:190: undefined reference to `skybolt::AltitudeBarModel::draw(float, float const*)'
/usr/bin/ld: /home/cel/Projekty/var/Skybolt/master/Skybolt-master/src/SkyboltExamples/ExamplesCommon/HudSystem.cpp:193: undefined reference to `skybolt::RollAngleRibbonModel::draw(float)'
/usr/bin/ld: ../../../lib/libExamplesCommon.a(HudSystem.cpp.o): in function `std::_MakeUniq<skybolt::HeadingRibbonModel>::__single_object std::make_unique<skybolt::HeadingRibbonModel, skybolt::VisHud*, skybolt::HeadingRibbonModel::Parameters&>(skybolt::VisHud*&&, skybolt::HeadingRibbonModel::Parameters&)':
/usr/include/c++/9/bits/unique_ptr.h:857: undefined reference to `skybolt::HeadingRibbonModel::HeadingRibbonModel(skybolt::HudDrawer*, skybolt::HeadingRibbonModel::Parameters const&)'
/usr/bin/ld: ../../../lib/libExamplesCommon.a(HudSystem.cpp.o): in function `std::_MakeUniq<skybolt::HudHoverVelModel>::__single_object std::make_unique<skybolt::HudHoverVelModel, skybolt::VisHud*, double, double>(skybolt::VisHud*&&, double&&, double&&)':
/usr/include/c++/9/bits/unique_ptr.h:857: undefined reference to `skybolt::HudHoverVelModel::HudHoverVelModel(skybolt::HudDrawer*, float, float)'
/usr/bin/ld: ../../../lib/libExamplesCommon.a(HudSystem.cpp.o): in function `std::_MakeUniq<skybolt::PitchLadderModel>::__single_object std::make_unique<skybolt::PitchLadderModel, skybolt::VisHud*, skybolt::PitchLadderModel::Parameters&>(skybolt::VisHud*&&, skybolt::PitchLadderModel::Parameters&)':
/usr/include/c++/9/bits/unique_ptr.h:857: undefined reference to `skybolt::PitchLadderModel::PitchLadderModel(skybolt::HudDrawer*, skybolt::PitchLadderModel::Parameters const&)'
/usr/bin/ld: ../../../lib/libExamplesCommon.a(HudSystem.cpp.o): in function `std::_MakeUniq<skybolt::AltitudeBarModel>::__single_object std::make_unique<skybolt::AltitudeBarModel, skybolt::VisHud*, skybolt::AltitudeBarModel::Parameters&>(skybolt::VisHud*&&, skybolt::AltitudeBarModel::Parameters&)':
/usr/include/c++/9/bits/unique_ptr.h:857: undefined reference to `skybolt::AltitudeBarModel::AltitudeBarModel(skybolt::HudDrawer*, skybolt::AltitudeBarModel::Parameters const&)'
/usr/bin/ld: ../../../lib/libExamplesCommon.a(HudSystem.cpp.o): in function `std::_MakeUniq<skybolt::RollAngleRibbonModel>::__single_object std::make_unique<skybolt::RollAngleRibbonModel, skybolt::VisHud*, skybolt::RollAngleRibbonModel::Parameters&>(skybolt::VisHud*&&, skybolt::RollAngleRibbonModel::Parameters&)':
/usr/include/c++/9/bits/unique_ptr.h:857: undefined reference to `skybolt::RollAngleRibbonModel::RollAngleRibbonModel(skybolt::HudDrawer*, skybolt::RollAngleRibbonModel::Parameters const&)'
collect2: error: ld returned 1 exit status

I was able to go around this by changing src/SkyboltExamples/FlightSimApp/CMakeLists.txt:
set(LIBS
-Wl,--start-group
AircraftHud
ExamplesCommon
-Wl,--end-group
)

**Comment by matthew-reid** [comment]
Thanks for pointing that out. I have now fixed this on the master branch.
