### ISSUE TITLE
Error while building due to Catch2 and OSG

### ISSUE THREAD

**Issue by felipunky** [Piraxus/Skybolt#9]
![image](https://user-images.githubusercontent.com/21000020/161439686-5fca74d2-5e2d-4007-b2bc-088f2c5d2ec3.png)
Using the latest of both libraries. 
Help much appreciated!

**Comment by matthew-reid** [comment]
Can you please try using the version of catch in this repository: https://github.com/Piraxus/SkyboltDependenciesHeaderOnly

Simply add the above repository root directory to your CMAKE_PREFIX_PATH and it should find the correct versions of the header only dependencies, including Catch.

Please also ensure the path to your OSG folder is in the CMAKE_PREFIX_PATH. Your OSG folder should contain subfolders named bin, include and lib. The include folder should have a file named 'Version' which the find script looks for.

**Comment by BenJ778** [comment]
Thank u for your help Matthew
